In [1]:
import numpy as np
def myNN(x):
    W = np.array([0.2, -0.1, 0.3])
    b = 0
    seta = 0
    v = np.sum(x * W) + b

    #activateion 
    y = v if v>seta else 0
    return y



ds = np.array([[0.3,0.1,0.8],
               [0.5,0.6,0.3],
               [0.1,0.2,0.1],
               [0.8,0.7,0.7],
               [0.5,0.5,0.6]])

for i in range(5):
    print(ds[i,:])
    print(myNN(ds[i,:]))

[0.3 0.1 0.8]
0.29
[0.5 0.6 0.3]
0.13
[0.1 0.2 0.1]
0.03
[0.8 0.7 0.7]
0.30000000000000004
[0.5 0.5 0.6]
0.22999999999999998
